spring:
  application:
    name: spring-boot-sample
  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboottest?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080
#  ssl:
#    key-store: 'classpath:mykeys.jks'
#    key-store-password: password
#    key-password: password
#  http2:
#    enabled: true
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#    min-response-size: 1024